### ISSUE TITLE
Some CSS style tags not working in export

### ISSUE THREAD

**Issue by psistorm** [oatear/cider#14] opened 2022-03-07 16:14 UTC
I found that when working with CSS grid it is properly displayed in the UI but the export is not working properly.

I attached below the file content I was using and how it should look like (left, bottom-left, bottom-middle, bottom-right are square images - don't mind the colors please. Just fiddling around with the tool :))

![image](https://user-images.githubusercontent.com/401902/157073195-dad702e9-ff6a-443e-b936-adc32cb78f31.png)

1. grid-area is not recognized at all by the export (change div classes from one to onename, two to twoname, ...)
2. Overlapping grid parts are not displayed correctly and used spacings/margins are also somehow a bit different in export
3. CSS Tricks with `:after` to display an icon behind a div are also not working in the export.

See also: [database.zip](https://github.com/oatear/cider/files/8199129/database.zip)

```
<html>
    <head>
        <style type="text/css">
            .cutframe {
                margin: 0px;
                width: 1111px;
                height: 816px;
                background-color: hsl(0, 0%, 90%);
                border: 36px solid hsl(0, 0%, 90%);
                color: hsl(0, 0%, 90%);
                font-family: "Segoe UI", Arial, sans-serif;
                font-size: 33px;
            }
            .card {
                width: 1039px;
                height: 744px;
                border-radius: 25px;
                background-color: hsl(0, 0%, 40%);
                border: 36px solid hsl(0, 0%, 100%);
                display: grid;
                grid-template-columns: 225px auto 225px auto 141px 84px;
                grid-template-rows: 15px 84px 20px 106px auto 225px;
                grid-template-areas: 
                    "one . . . . ."
                    "one header header header header number"
                    "one . . . . ."
                    "one content content content content content"
                    "leftlink content content content content content"
                    "two bottom1 three bottom2 four four";
                column-gap: 0;
                row-gap: 0;
            }
            .card>.icon img {
                width: 225px;
                border-radius: 25px;
            }
            .card .one {
                grid-row: 1 / 4;
                grid-column: 1;
            }
            .card .two {
                grid-row: 6;
                grid-column: 1;
            }
            .card .three {
                grid-row: 6;
                grid-column: 3;
            }
            .card .four {
                grid-row: 6;
                grid-column: 5 / 6;
            }
            .card .onename {
                grid-area: one;
            }
            .card .two {
                grid-area: two;
            }
            .card .three {
                grid-area: three;
            }
            .card .four {
                grid-area: four;
            }            
            .card .header {
                background-color: #f2a029;
                color: #ffffff;
                grid-area: header;
                font-size: 48px;
                padding-left: 20px;
                line-height: 84px;
            }                        
            .card .header span {
                display: inline-block;
                vertical-align: middle;
                font-family: "Segoe UI", Arial, sans-serif;
                text-transform: uppercase;
            }
            .card .number {
                grid-area: number;
                padding-left: 0 !important;
                background-color: #ffffff;
                color: #000000;
                font-weight: 800;
                font-family: sans-serif;
                text-align: center;
            }
            .card .content {
                grid-area: content;
                padding-left: 45px;
            }
            .card .content div:not(:last-child) {
                margin-bottom: 20px;
            }
            .card .content > div.effect {
                background-color: #ffffffaa;
                color: #000000;
                padding: 10px;
                padding-left: 40px;
                padding-right: 10px;
                line-height: 1.3;
            }
            div.effect > .icon {
                margin-left: -65px;
                margin-top: -3px;
                float: left;
                width: 50px;
                height: 50px;
            }
            div.effect > .icon:after {
                content: " ";
                text-indent: -999em;
                display: block;
                background: url("ressources/behind.svg");
                background-size: 70px;
                margin: -60px 0 0 -10px;
                width: 70px;
                height: 70px;
            }
        </style>
    </head>
    <body>
<div class="cutframe">
    <div class="card">
        <div class="header"><span>Title</span></div>
        <div class="header number"><span>1</span></div>
        <div class="content">
            <div class="effect">
                Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
            </div>
            <div class="effect">
                Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua
            </div>
        </div>
        <div class="icon one"><img src="ressources/image-1.svg" /></div>
        <div class="icon two"><img src="ressources/image-2.svg" /></div>
        <div class="icon three"><img src="ressources/image-3.svg" /></div>
        <div class="icon four"><img src="ressources/image-4.svg" /></div>
    </div>
</div>
    </body>
</html>
```

**Comment by psistorm** [comment] 2022-03-07 16:18
[card-sheets (14).pdf](https://github.com/oatear/cider/files/8199172/card-sheets.14.pdf)

This is how the export looks like (it's the same for the images).

**Comment by hristoiankov** [comment] 2022-03-07 18:01
I just imported your database.json and ran the PDF export.  Everything comes out as expected for me: 
[card-sheets.pdf](https://github.com/oatear/cider/files/8199879/card-sheets.pdf)

What OS, browser, and screen dimensions are you using?  I'm on Ubuntu on latest Chromium with a 1600x900 screen.

**Comment by psistorm** [comment] 2022-03-07 19:24
That is pretty strange... Windows 10, Google Chrome latest version and 34 inch screen with 3440x1440.

Don't know if this changes something but I cloned the repo with newest version and started it locally. Node version 17.6

**Comment by hristoiankov** [comment] 2022-03-07 21:15
Do you get the same behavior if you run the export on the GitHub pages hosted application?

https://oatear.github.io/cider/

**Comment by psistorm** [comment] 2022-03-07 21:51
Yes it's the same. I also reset the database, launched it again in Incognito mode. Doesn't change the result, unfortunately. I also tried to emulate the page in a different screen size via Chrome developer tools. Doesn't change anything.

**Comment by hristoiankov** [comment] 2022-03-08 00:55
Does the export preview look like this for you, or is the styling there incorrect?

![image](https://user-images.githubusercontent.com/35353708/157144192-48c0e78b-dde6-41b0-bbba-33553c0c1c53.png)

Could you also try another browser, Ex. Firefox?

**Comment by hristoiankov** [comment] 2022-03-08 05:26
I pushed some changes to production in the way the previews are rendered.  That change may have fixed/changed this issue.

**Comment by psistorm** [comment] 2022-03-08 08:26
So I tried out Firefox, which works! Chrome not...This is my Chrome version:
![2022-03-08 09_23_20-Einstellungen – Über Google Chrome](https://user-images.githubusercontent.com/401902/157196565-e6f956bf-7c06-4d6f-920a-b906c6f8061c.png)#

This is how the export preview looks like
![2022-03-08 09_21_50-Cider](https://user-images.githubusercontent.com/401902/157196562-f685bdf8-3245-4f82-9c81-01bcd361f1dd.png)

And this is how it looks when export is done:
![front-7](https://user-images.githubusercontent.com/401902/157196641-7d5fe4a9-74b2-4f02-b34b-86f99996ed85.png)

**Comment by psistorm** [comment] 2022-03-08 09:38
One correction: The :after Feature with a shadow DOM is not also not working for export in Firefox. Preview is shown correctly.

**Comment by hristoiankov** [comment] 2022-03-08 12:19
Do you have any browser add-ons like ad-block? The pdf library (pdfMake) I am currently using seems to not work well with ad-block.  I might swap it out tonight for jsPdf since it also won’t work on iPad/iPhone.

However from your screenshots, it looks like the export preview you attached is the individual images export preview, and the export you’re showing is the Sheet export (PDF). Does the sheet export preview also look correct?

**Comment by psistorm** [comment] 2022-03-08 12:24
I have uBlock Origin and AdBlock both disabling both doesn't change anything. Both previews of Individual Image Export and Sheet Export look the same and look fine. Both exports look also the same...not correct.

**Comment by hristoiankov** [comment] 2022-03-08 13:26
After updating my windows machine to the latest Chrome, I am finally seeing this issue.  I should be able to make progress now.

**Comment by hristoiankov** [comment] 2022-03-08 22:05
Information for reproducibility.

Working Chrome:
Version 98.0.4758.82 (Official Build) (64-bit)

Not working Chrome:
Version 99.0.4844.51 (Official Build) (64-bit)

**Comment by hristoiankov** [comment] 2022-03-08 22:24
It seems that the Chromium team really mucked things up with the latest release.

"Looks like Chrome Version 99 (and Edge 99) seemingly have broken canvas exports. Firefox Dev Edition seems to work.
I have the same problem with html-to-image and react-component-export-image. I am also using CSS grid as I mentioned here"
https://github.com/tsayen/dom-to-image/issues/410
https://github.com/niklasvh/html2canvas/issues/2853

This Chrome release came out March 1 (7 days ago).  We could wait it out for another few days.

Their changelog is full of changes to the Canvas so its hard to track down which one particularly is the cause here.

**Comment by psistorm** [comment] 2022-03-09 09:32
Sure, just wait a bit and see if there will come up any fixes by the 3rd party library oder Chrome itself.

**Comment by hristoiankov** [comment] 2022-03-09 19:54
https://github.com/bubkoo/html-to-image/issues/258

**Comment by hristoiankov** [comment] 2022-03-14 14:08
I opened up a ticket on the Chromium project for this as well since it affects more than just html-to-image, but all other html to canvas libraries.

https://bugs.chromium.org/p/chromium/issues/detail?id=1305997

**Comment by hristoiankov** [comment] 2022-03-31 11:55
Good news.  The Chromium team has written a fix for this and its coming out with their official M102 release.  I will close this ticket once that release comes out.

**Comment by hristoiankov** [comment] 2022-07-02 14:59
Confirmed working fix. Latest public release chrome is M103.

**Closed by hristoiankov** 2022-07-02 14:59 UTC
Labels: bug
